version: '3'
services:
  node:
    build: .
    ports:
     - "4000:4000"    
    expose:
      - "4000"   
    links:
      - mysql
    depends_on:
      - mysql    
  mysql:
    image: "mysql/mysql-server"
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: clip
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234    
    expose:
      - "3306"

